### ISSUE TITLE
Is it legal?

### ISSUE THREAD

**Issue by fpdragon** [pagong/arduino-yksim#1]
Hello and sorry for writing this way. This is not a bug report but I can't find any other way to get in touch.

Great project and really great thing you did there!

I'm still wondering if this is really legal?
YubiCo is a company and they sell sticks with the YubiKey OTP process. The verification process happens through their servers. Somehow I can't quite imagine that the company YubiCo tolerates that their processes and products could be easily replaced by open source products?
Maybe they have any patents or utility models?
But I'll admit quite frankly: I have no idea.

I would also like to use this library and possibly also for my customer projects, but I would have to know whether this is really allowed.

Hope someone can help me here.

**Comment by pagong** [comment]
The code of `arduino-yksim` is based on Yubico's repo `yubico-c`.
License is BSD: https://github.com/Yubico/yubico-c?tab=readme-ov-file#license
