### ISSUE TITLE
Update to work with newer IDE versions

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [pagong/arduino-yksim#2]
I currently cannot build this due to how outdated it is

**Comment by vanten-s** [comment]
I'm trying to fork the project. It will hopefully work sometime in the future lol

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
Thank the lord almighty.
Could you also add support for Arduino Uno(s) on custom firmware?

**Comment by pagong** [comment]
"arduino-yksim" has been archived. Please see [arduino2-yksim](https://github.com/pagong/arduino2-yksim) for it's successor!
